### ISSUE TITLE
Экспорт в Excel

### ISSUE THREAD

**Issue by FrediKats** [kysect/GithubActivityAnalyzer#6]
В первом приближении хотелось бы получить функионал экспорта полученного результата в эксель. Это будет создаваемый по указанному пути файл в котором будет список из юзернеймов и их суммарной активности. Также, должны быть заголовки этих столбцов. Добавить возможность экспортировать подробную статистику по группе и студентам.

**Comment by TomGnill** [comment]
Сделал так, чтобы теперь в инфу вносился и текущий месяц, по какой-то причине апрель в ячейке отображается как решётки.
